[target.x86_64-apple-darwin]
image = "ghcr.nju.edu.cn/cross-rs/x86_64-apple-darwin-cross"
[target.aarch64-apple-darwin]
image = "ghcr.nju.edu.cn/cross-rs/aarch64-apple-darwin-cross"
[target.aarch64-linux-android]
image = "ghcr.nju.edu.cn/cross-rs/aarch64-linux-android:main"
[target.aarch64-unknown-linux-gnu]
image = "ghcr.nju.edu.cn/cross-rs/aarch64-unknown-linux-gnu:main"